"""Cambios para quitar frases repetidas entre artículos publicados (6-10-2026).
Cada cambio: (ID, motivo, texto exacto actual, texto nuevo). Solo cambia texto; no toca estado, enlaces ni cifras.
"""
P165 = "<strong>0,165 €/kWh con impuestos incluidos</strong>"
CAMBIOS = [
 # --- Aviso del precio de referencia (se queda igual solo en el 16, aire acondicionado) ---
 (17, "Aviso de precio repetido",
  f"Todas las cuentas usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo y todo se ajusta en la misma proporción.",
  f"Para comparar la freidora con el horno tomamos un precio de {P165}: 0,13 € de energía más el impuesto eléctrico y el IVA. Con otro precio cambian los euros, pero no cuál de los dos sale más barato: multiplica cada cifra por tu precio y divídela entre 0,165."),
 (18, "Aviso de precio repetido",
  f"Estas cifras usan un precio de {P165} (0,13 €/kWh de energía más impuesto eléctrico e IVA). Si en tu factura el kWh sale a otro precio, cámbialo: el coste sube o baja en la misma proporción.",
  f"El kWh lo contamos a {P165}, que es lo que sale con 0,13 € de energía tras sumar el impuesto eléctrico y el IVA. Si tu factura dice otra cosa, pon tu precio: cada importe crece o baja en la misma medida."),
 (19, "Aviso de precio repetido",
  f"Los cálculos usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si en tu factura pagas otra cantidad, cambia ese precio: el resultado sube o baja en la misma proporción.",
  f"Usamos como referencia {P165} (energía a 0,13 €/kWh, más impuesto eléctrico e IVA). Busca en tu factura lo que pagas tú por kWh y ajusta: con un precio un 10 % más alto, el termo te costará un 10 % más."),
 (20, "Aviso de precio repetido",
  f"Todos los cálculos usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo: el resultado varía en la misma proporción.",
  f"La nevera está enchufada todo el año, así que el precio importa. Calculamos con {P165}, que sale de 0,13 € de energía más el impuesto eléctrico y el IVA; si el tuyo es distinto, el gasto cambia en la misma proporción."),
 (95, "Aviso de precio repetido",
  f"Todas las cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo: el resultado sube o baja en la misma proporción.",
  f"Para poner todos los sistemas en la misma balanza, la electricidad se paga a {P165} (0,13 € de energía, más el impuesto eléctrico y el IVA). Si tu kWh cuesta otra cosa, los importes cambian, pero el orden de qué calefacción sale más barata se mantiene."),
 (96, "Aviso de precio repetido",
  f"Las cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo: el ahorro sube o baja en la misma proporción.",
  f"El precio de referencia es de {P165}: la energía a 0,13 € con el impuesto eléctrico y el IVA ya incluidos. Cuanto más caro te salga el kWh, más ahorras con la bomba de calor, y al revés, en la misma proporción."),
 (97, "Aviso de precio repetido",
  f"Las cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo y los resultados cambian en la misma proporción.",
  f"Los tres aparatos se comparan con la luz a {P165} (0,13 € por kWh de energía, más el impuesto eléctrico y el IVA). Tu precio puede ser otro: los euros cambian, la comparación entre ellos no."),
 (98, "Aviso de precio repetido",
  f"Estas cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo y el coste sube o baja en la misma proporción.",
  f"El coste se calcula con un precio de {P165}, resultado de sumar el impuesto eléctrico y el IVA a 0,13 € de energía. ¿Tu factura marca otro precio? Haz una regla de tres con 0,165 y tendrás tu coste."),
 (104, "Aviso de precio repetido",
  f"Estas cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo y el coste sube o baja en la misma proporción.",
  f"Calculamos con la luz a {P165} (0,13 € de energía más impuesto eléctrico e IVA). Para tu caso, cambia ese precio por el de tu factura y el gasto de los emisores se ajusta en la misma proporción."),
 (105, "Aviso de precio repetido",
  f"Estas cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo y el coste sube o baja en la misma proporción.",
  f"La referencia es un kWh a {P165}, es decir, 0,13 € de energía más el impuesto eléctrico y el IVA. Una manta gasta tan poco que, con un precio algo distinto, la diferencia será de céntimos; aun así, puedes poner el tuyo y recalcular."),
 (106, "Aviso de precio repetido",
  f"Estas cifras usan un precio de {P165} (0,13 €/kWh de energía más el impuesto eléctrico y el IVA). Si tu factura tiene otro precio, cámbialo y el coste sube o baja en la misma proporción.",
  f"Las cuentas del deshumidificador están hechas con {P165} (0,13 € de energía, a los que se suman el impuesto eléctrico y el IVA). Si pagas otro precio, sustitúyelo: su coste sube o baja en la misma proporción."),
 # --- Introducciones con la misma plantilla que la del radiador de aceite (18) ---
 (98, "Introducción calcada de la del radiador",
  "¿Cuánto consume una estufa eléctrica? Una de 2.000 W gasta de media unos 1,7 kWh por hora de uso, lo que cuesta 0,28 € la hora. Con 3 horas al día son 0,84 € diarios y 25,58 € al mes, y un invierno de cuatro meses se va a 102,33 €.",
  "¿Cuánto consume una estufa eléctrica? Una de 2.000 W tira de casi toda su potencia mientras está encendida: unos 1,7 kWh por hora, es decir, 0,28 € cada hora. Con 3 horas diarias de uso, pagas 0,84 € al día y 25,58 € al mes; en un invierno de cuatro meses, 102,33 €."),
 (104, "Introducción calcada de la del radiador",
  "¿Cuánto consumen los emisores térmicos? Uno de 1.000 W gasta de media unos 0,6 kWh por hora de uso, lo que cuesta 0,10 € la hora. Con 5 horas al día son 0,50 € diarios y 15,05 € al mes, y un invierno de cuatro meses se queda en 60,19 €.",
  "¿Cuánto consumen los emisores térmicos? Un emisor de 1.000 W, con su termostato cortando a ratos, se queda en unos 0,6 kWh por hora: 0,10 € cada hora de uso. Encendido 5 horas al día, son 0,50 € diarios, 15,05 € al mes y 60,19 € en un invierno de cuatro meses."),
 # --- FAQ «de 1.500 W»: el 104 era idéntico al 18 ---
 (104, "Respuesta de FAQ idéntica a la del radiador",
  "Con un uso real del 60 %, unos 0,9 kWh por hora: 0,15 € la hora, 0,74 € al día con 5 horas de uso y 22,57 € al mes.",
  "Unos 0,9 kWh por hora, porque el termostato lo tiene encendido alrededor del 60 % del tiempo. Son 0,15 € la hora; con 5 horas diarias, 0,74 € al día y 22,57 € al mes."),
 (98, "Respuesta de FAQ con la misma plantilla",
  "Con un uso real del 85 %, unos 1,28 kWh por hora: 0,21 € la hora, 0,63 € al día con 3 horas de uso y 19,19 € al mes.",
  "Como pasa casi todo el rato con la resistencia encendida (un 85 %), gasta unos 1,28 kWh por hora: 0,21 €. Con 3 horas al día, 0,63 € diarios y 19,19 € al mes."),
 # --- Frases de explicación repetidas ---
 (104, "Frase repetida con calefacción eléctrica más barata",
  "Y una resistencia convierte cada kWh de electricidad en un kWh de calor, ni más ni menos.",
  "Toda la electricidad que entra en una resistencia sale convertida en calor: 1 kWh gastado, 1 kWh de calor."),
 (104, "Frase repetida con la estufa",
  "La tabla recoge las potencias más habituales. Aplicamos un factor de uso real de 0,6:",
  "En la tabla verás las potencias más comunes, calculadas con un factor de uso real de 0,6:"),
 (106, "Frase repetida con la estufa",
  "Aplicamos un factor de uso real de 0,8: el aparato tiene un humidistato que lo para cuando el aire llega a la humedad marcada, y el compresor no trabaja todo el rato. Es el mismo criterio que usa nuestra calculadora de consumo.",
  "Para el cálculo usamos un factor de uso real de 0,8, igual que nuestra calculadora de consumo: el aparato tiene un humidistato que lo para cuando el aire llega a la humedad marcada, y el compresor no trabaja todo el rato."),
 (98, "Frase repetida con radiador, convector o calefactor",
  "A igual potencia, lo mismo por cada hora con la resistencia encendida.",
  "Mientras la resistencia está encendida, dos aparatos de la misma potencia gastan exactamente lo mismo por hora."),
 (98, "Frase repetida con la freidora",
  "La potencia está en la placa de características, normalmente en la parte de atrás o debajo, y en la caja.",
  "Para saber la potencia de la tuya, busca la placa de características, que suele estar detrás o debajo, o mira la caja."),
 (18, "Frase repetida con calefacción eléctrica más barata",
  "Lo que cambia es cómo reparten ese calor:",
  "La diferencia está en la forma de repartir ese calor:"),
 (96, "Frase repetida con calefacción eléctrica más barata",
  "El invierno se cuenta como 4 meses.",
  "Para el invierno contamos 4 meses."),
 # --- Tarifa por tramos: misma frase en 4 artículos (se queda en el 16 y el 18) ---
 (98, "Frase de tramos repetida",
  "Con la tarifa 2.0TD con discriminación horaria, el precio cambia según la franja. Así sale una estufa de 2.000 W usada 3 horas al día:",
  "Si pagas la luz por tramos, la misma estufa cuesta más del doble en punta que en valle. Estos son los importes de una de 2.000 W encendida 3 horas al día en cada franja:"),
 (104, "Frase de tramos repetida",
  "Con la tarifa 2.0TD con discriminación horaria, el mismo emisor cuesta muy distinto según la franja. Así sale un emisor de 1.000 W usado 5 horas al día:",
  "Si tu contrato tiene precios por tramos (peaje 2.0TD), mira a qué hora lo enciendes. Un emisor de 1.000 W durante 5 horas diarias cuesta esto según la franja:"),
 (106, "Frase de tramos repetida",
  "Con la tarifa 2.0TD con discriminación horaria, el precio del kWh depende de la franja. Así sale un deshumidificador de 250 W, 8 horas al día:",
  "Como el deshumidificador puede funcionar a cualquier hora, con una tarifa por tramos compensa elegir cuándo. Así, en cada franja, salen estos costes para uno de 250 W que funciona 8 horas al día:"),
 # --- Pasos del enchufe medidor: iguales en estufa y manta ---
 (105, "Pasos iguales que en la estufa",
  "Enchufa la manta al medidor y úsala como siempre durante una semana.",
  "Conecta la manta a través del medidor y úsala como cualquier otra noche durante una semana."),
 (105, "Pasos iguales que en la estufa",
  "Apunta los kWh que marca al final y divídelos entre 7 para tener el consumo de una noche.",
  "Al séptimo día, divide entre 7 los kWh acumulados: ese es el gasto de una noche."),
 (105, "Pasos iguales que en la estufa",
  "Multiplica por el precio del kWh de tu factura y por 30,4 para sacar el coste al mes.",
  "Para el mes, multiplica ese gasto por 30,4 y por el precio del kWh que pagas."),
 # --- Avisos de seguridad repetidos ---
 (98, "Aviso de seguridad igual que en radiador, convector o calefactor",
  "Enchúfala directamente a la pared. Evita regletas y alargadores finos: a 2.000 W el cable se puede calentar.",
  "Conéctala a un enchufe de pared: las regletas y los alargadores finos pueden calentarse con 2.000 W."),
 (137, "Aviso de seguridad igual que en la estufa",
  "<strong>Si el enchufe o la clavija se calientan</strong>, deja de cargar y llama a un instalador autorizado.",
  "<strong>Si notas caliente la toma o la clavija</strong>, para la carga y pide a un instalador autorizado que la revise."),
 # --- Cierre: final idéntico en 92 y 93 (la frase obligatoria de CLAUDE.md se mantiene) ---
 (93, "Final del cierre idéntico al de cómo leer la factura",
  "pon tus aparatos, tu potencia contratada y los precios de tu factura.</p>",
  "mete los aparatos que sueles encender a la vez y comprueba si tu potencia contratada se queda corta o te sobra.</p>"),
 # --- Segunda pasada ---
 (98, "Frases repetidas con radiador de aceite y freidora",
  "La tabla recoge las potencias más habituales. Aplicamos un factor de uso real de 0,85: aunque la estufa tenga termostato, suele usarse para calentar rápido y pasa la mayor parte del tiempo con la resistencia encendida. Es el mismo criterio que usa nuestra calculadora de consumo.",
  "La tabla recoge las potencias más habituales, con un factor de uso real de 0,85: aunque la estufa tenga termostato, suele usarse para calentar rápido y pasa la mayor parte del tiempo con la resistencia encendida. Nuestra calculadora de consumo usa ese mismo valor."),
 (18, "Horario de tramos escrito igual que en calefacción eléctrica más barata",
  "El valle va de 0 a 8 h y dura todo el fin de semana; la punta, de 10 a 14 h y de 18 a 22 h.",
  "Valle son las horas de 0 a 8 y el fin de semana completo; punta, de 10 a 14 h y de 18 a 22 h."),
 (18, "Pregunta frecuente casi igual que en radiador, convector o calefactor",
  "¿Gasta menos un radiador de aceite que un calefactor?",
  "¿Ahorro algo si cambio el calefactor por un radiador de aceite?"),
 (105, "Frase de enlace igual que en radiador, convector o calefactor",
  "Tienes el detalle de esos aparatos en <a href=\"https://tuluzencasa.com/cuanto-consume-radiador-de-aceite/\">cuánto consume un radiador de aceite</a> y en <a",
  "Si quieres comparar con más calma, mira <a href=\"https://tuluzencasa.com/cuanto-consume-radiador-de-aceite/\">cuánto consume un radiador de aceite</a> y <a"),
 # --- Tercera pasada (6-10-2026, tarde) ---
 (137, "Horario del valle escrito igual que en tramos horarios",
  "El valle va de 0 a 8 h de lunes a viernes y todo el día los sábados, domingos y festivos nacionales.",
  "Las horas valle son las de 0 a 8 entre semana y los sábados, domingos y festivos nacionales enteros."),
 (94, "Respuesta casi igual que en bono social eléctrico",
  "El bono social solo se aplica a contratos con una comercializadora de referencia. Si estás en mercado libre y cumples los requisitos, tienes que pasarte al PVPC para pedirlo.",
  "Para tener bono social hay que estar en el PVPC de una comercializadora de referencia, así que, si estás en el mercado libre y cumples los requisitos, tendrás que cambiarte para pedirlo."),
 (106, "Respuesta con la misma plantilla que en la manta eléctrica",
  "Uno de 250 W, 24 horas, unos 4,8 kWh:",
  "Si un aparato de 250 W no para en todo el día, gasta unos 4,8 kWh:"),
]
