  var A=[
    {id:'ac',g:'Climatización',n:'Aire acondicionado 3.000 frigorías',w:1000,h:6,d:7,f:'tarde',r:0.6},
    {id:'rad',g:'Climatización',n:'Radiador de aceite 2.000 W',w:2000,h:4,d:7,f:'punta',r:0.6,alt:{n:BOMBA,k:0.35,c:700}},
    {id:'est',g:'Climatización',n:'Estufa o calefactor 2.000 W',w:2000,h:3,d:7,f:'punta',r:0.85,alt:{n:BOMBA,k:0.3,c:700}},
    {id:'bdc',g:'Climatización',n:'Bomba de calor (calefacción)',w:900,h:6,d:7,f:'punta',r:0.7},
    {id:'des',g:'Climatización',n:'Deshumidificador',w:250,h:8,d:7,f:'todo',r:0.8},
    {id:'ven',g:'Climatización',n:'Ventilador',w:50,h:8,d:7,f:'tarde',r:1},
    {id:'man',g:'Climatización',n:'Manta eléctrica',w:100,h:8,d:7,f:'madrugada',r:0.5},
    {id:'ter',g:'Agua caliente',n:'Termo eléctrico 80 L',s:'el termo',w:1500,h:3,d:7,f:'todo',r:0.7,m:1},
    {id:'hor',g:'Cocina',n:'Horno eléctrico',w:2200,h:0.75,d:4,f:'punta',r:0.6,alt:{n:'una freidora de aire (para raciones pequeñas)',k:0.5,c:90}},
    {id:'fre',g:'Cocina',n:'Freidora de aire',w:1500,h:0.33,d:5,f:'punta',r:0.7},
    {id:'ind',g:'Cocina',n:'Placa de inducción (un fuego)',w:1800,h:1,d:7,f:'manana',r:0.7},
    {id:'vit',g:'Cocina',n:'Vitrocerámica (un fuego)',w:1800,h:1,d:7,f:'manana',r:0.75,alt:{n:'una placa de inducción',k:0.75,c:400}},
    {id:'mic',g:'Cocina',n:'Microondas',w:1000,h:0.25,d:7,f:'manana',r:1},
    {id:'her',g:'Cocina',n:'Hervidor de agua',w:2000,h:0.1,d:7,f:'manana',r:1},
    {id:'caf',g:'Cocina',n:'Cafetera',w:1000,h:0.15,d:7,f:'manana',r:1},
    {id:'nev',g:'Cocina',n:'Nevera combi',w:150,h:24,d:7,f:'todo',r:0.2,alt:{n:'una nevera nueva de clase A o B',k:0.5,c:650,nota:'Solo si la tuya tiene más de 12 años.'}},
    {id:'con',g:'Cocina',n:'Congelador vertical',w:150,h:24,d:7,f:'todo',r:0.2},
    {id:'lav',g:'Lavado',n:'Lavadora (lavado a 40 °C)',s:'la lavadora',w:800,h:1,d:4,f:'manana',r:1,m:1},
    {id:'sev',g:'Lavado',n:'Secadora de evacuación',s:'la secadora',w:2500,h:1,d:3,f:'tarde',r:0.8,m:1,alt:{n:'una secadora con bomba de calor',k:0.45,c:550}},
    {id:'seb',g:'Lavado',n:'Secadora con bomba de calor',s:'la secadora',w:900,h:1.5,d:3,f:'tarde',r:0.8,m:1},
    {id:'lvv',g:'Lavado',n:'Lavavajillas (programa eco)',s:'el lavavajillas',w:1200,h:1.5,d:5,f:'punta',r:0.55,m:1},
    {id:'pla',g:'Lavado',n:'Plancha',w:2200,h:0.5,d:2,f:'tarde',r:0.5},
    {id:'tv',g:'Ocio y oficina',n:'Televisión de 55 pulgadas',w:100,h:4,d:7,f:'punta',r:1},
    {id:'pc',g:'Ocio y oficina',n:'Ordenador gaming',w:400,h:4,d:7,f:'tarde',r:0.7},
    {id:'por',g:'Ocio y oficina',n:'Portátil',w:60,h:6,d:5,f:'manana',r:0.7},
    {id:'vid',g:'Ocio y oficina',n:'Videoconsola',w:150,h:2,d:7,f:'punta',r:1},
    {id:'rou',g:'Ocio y oficina',n:'Router wifi',w:10,h:24,d:7,f:'todo',r:1},
    {id:'sby',g:'Ocio y oficina',n:'Aparatos en espera (standby)',w:15,h:24,d:7,f:'todo',r:1,alt:{n:'regletas con interruptor',k:0.3,c:25}},
    {id:'led',g:'Iluminación',n:'Iluminación LED (10 bombillas)',w:90,h:5,d:7,f:'punta',r:1},
    {id:'hal',g:'Iluminación',n:'Iluminación halógena (10 bombillas)',w:500,h:5,d:7,f:'punta',r:1,alt:{n:'bombillas LED equivalentes',k:0.15,c:40}},
    {id:'car',g:'Movilidad',n:'Cargador de coche eléctrico 7,4 kW',s:'la carga del coche',w:7400,h:2,d:5,f:'madrugada',r:1,m:1},
    {id:'asp',g:'Otros',n:'Aspiradora',w:800,h:0.5,d:3,f:'manana',r:1},
    {id:'sec',g:'Otros',n:'Secador de pelo',w:1800,h:0.2,d:7,f:'manana',r:1}
  ];